[env]
_.python.venv = { path = ".venv", create = true }

[tools]
python = "3.10"
uv = "0.7.4"

[settings]
idiomatic_version_file_enable_tools = []

[tasks.init]
run = ["mise install", "uv sync", "uvx pre-commit install"]
description = "Set up the development environment"

[tasks.pytest]
run = ["python -mpytest --cov=src/ --cov-report=term-missing tests/unit -v"]
description = "Run unit tests using pytest with coverage report"

[tasks.pytest-integration]
run = ["python -mpytest tests/integration -v"]
description = "Run integration tests using pytest"

[tasks.ci]
run = ["python -mtox p"]
description = "Run tests on multiple Python versions using tox"

[tasks.doc]
run = ["python -mmkdocs serve -o"]
description = "Build and serve package documentation"
